###############################################################################
#                           Users Database                                    #
###############################################################################

users:

  admin :
    displayname : "Administrator"
    password : "$argon2id$v=19$m=65536,t=3,p=4$m885eAKCb9CRporYgPhQ6A$WJ+Mb7ww7qsV+wCZvWvNK/egQKrYsGFZnrHuuPw+bdo"
    email : jerrod.sunderland@gmail.com
    groups:
      - users

  reg :
    displayname : "Regular User"
    password : "$argon2id$v=19$m=65536,t=3,p=4$kSYCykLbyOrnX6hdX+XOkQ$H3lt75XnOey2TJvFLDpObNxoSwmmAG9qUS/jYOGjDzU"
    email : user@yourdomain.com
    groups:
      - users

